import Head from "next/head";
import { Box } from "@mantine/core";
import Header from "@/features/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Audiophile Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={() => ({
          backgroundColor: "black",
        })}
      >
        <Header />
      </Box>
    </>
  );
}
